name: Deploy Staging

on:
  push:
    branches: [ staging ]

jobs:
  distribute-android:
    runs-on: ubuntu-latest
    steps:
      # Node
      - uses: actions/checkout@v4
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: YARN Cache
        uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: YARN Install
        run: |
          echo "${{ secrets.ENV }}" > .env
          sed -i -e 's/ && cd ios && pod install && cd ..//g' package.json
          yarn install

      # Build
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install firebase tool
        run: |
          yarn global add firebase-tools
      # - name: Bundle Cache
      #   uses: actions/cache@v4
      #   with:
      #     path: android/vendor/bundle
      #     key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-gems-
      # - name: Setup fastlane
      #   run: |
      #     cd android && bundle install
      - name: Distribute to firebase
        run: yarn env:stag && yarn prebuild:clean && yarn fastlane-android:stag

  distribute-ios:
    runs-on: macOS-26
    steps:
      # Node
      - uses: actions/checkout@v4
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: YARN Cache
        uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Pods Cache
        uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: YARN Install
        run: |
          echo "${{ secrets.ENV }}" > .env
          yarn install

      # Build
      - name: Distribute to firebase
        run: yarn env:stag && yarn prebuild:clean && yarn fastlane-ios:stag
